language: node_js

node_js:
  - '8.4'

branches:
  only:
    - master

cache:
  yarn: true
  
before_publish:
  - yarn global add vsce
  - gulp

script:
  - gulp
  

publish:
  - vsce package
  - vsce publish -p $TOKEN_VSCODE